//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TM.SP.DataModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebPartsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebPartsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TM.SP.DataModel.WebPartsRes", typeof(WebPartsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;webParts&gt;
        ///  &lt;webPart xmlns=&quot;http://schemas.microsoft.com/WebPart/v3&quot;&gt;
        ///    &lt;metaData&gt;
        ///      &lt;type name=&quot;Microsoft.SharePoint.WebPartPages.XsltListViewWebPart, Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c&quot; /&gt;
        ///      &lt;importErrorMessage&gt;Cannot import this Web Part.&lt;/importErrorMessage&gt;
        ///    &lt;/metaData&gt;
        ///    &lt;data&gt;
        ///      &lt;properties&gt;
        ///        &lt;property name=&quot;ShowWithSampleData&quot; type=&quot;bool&quot;&gt;False&lt;/property&gt;
        ///        &lt;property name=&quot;Default&quot; type=&quot;string&quot; /&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IncomeRequestListViewXml {
            get {
                return ResourceManager.GetString("IncomeRequestListViewXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;webParts&gt;
        ///  &lt;webPart xmlns=&quot;http://schemas.microsoft.com/WebPart/v3&quot;&gt;
        ///    &lt;metaData&gt;
        ///      &lt;type name=&quot;TM.SP.AppPages.LicenseFilterWebPart, TM.SP.AppPages, Version=1.0.0.0, Culture=neutral, PublicKeyToken=63e92b7beac312db&quot; /&gt;
        ///      &lt;importErrorMessage&gt;Невозможно импортироватьве часть Фильтрация разрешений.&lt;/importErrorMessage&gt;
        ///    &lt;/metaData&gt;
        ///    &lt;data&gt;
        ///      &lt;properties&gt;
        ///        &lt;property name=&quot;ExportMode&quot; type=&quot;exportmode&quot;&gt;All&lt;/property&gt;
        ///        &lt;property name=&quot;HelpUrl&quot; type=&quot;string&quot; /&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LicenseFilterWebPartXml {
            get {
                return ResourceManager.GetString("LicenseFilterWebPartXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;webParts&gt;
        ///  &lt;webPart xmlns=&quot;http://schemas.microsoft.com/WebPart/v3&quot;&gt;
        ///    &lt;metaData&gt;
        ///      &lt;type name=&quot;Microsoft.SharePoint.WebPartPages.XsltListViewWebPart, Microsoft.SharePoint, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c&quot; /&gt;
        ///      &lt;importErrorMessage&gt;Невозможно импортировать эту веб-часть.&lt;/importErrorMessage&gt;
        ///    &lt;/metaData&gt;
        ///    &lt;data&gt;
        ///      &lt;properties&gt;
        ///        &lt;property name=&quot;ShowWithSampleData&quot; type=&quot;bool&quot;&gt;False&lt;/property&gt;
        ///        &lt;property name=&quot;Default&quot; type=&quot;string [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LicenseMoListViewXml {
            get {
                return ResourceManager.GetString("LicenseMoListViewXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;webParts&gt;
        ///  &lt;webPart xmlns=&quot;http://schemas.microsoft.com/WebPart/v3&quot;&gt;
        ///    &lt;metaData&gt;
        ///      &lt;type name=&quot;ListViewFilter.WebParts.SPListViewFilter.SPListViewFilter, ListViewFilter, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c2efc42ca9f77dc7&quot; /&gt;
        ///      &lt;importErrorMessage&gt;Cannot import this Web Part.&lt;/importErrorMessage&gt;
        ///    &lt;/metaData&gt;
        ///    &lt;data&gt;
        ///      &lt;properties&gt;
        ///        &lt;property name=&quot;AllowZoneChange&quot; type=&quot;bool&quot;&gt;True&lt;/property&gt;
        ///        &lt;property name=&quot;HelpUrl&quot; type=&quot;string&quot; /&gt;
        ///        &lt;pro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SPFilterListViewXml {
            get {
                return ResourceManager.GetString("SPFilterListViewXml", resourceCulture);
            }
        }
    }
}
